version: "3.9"

services:
  db:
    image: postgres:15.1-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  redis:
    image: redis:7.0.5-alpine
    command: redis-server
    ports:
      - ${REDIS_PORT:-6379}:6379
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis:/data

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - ${WEB_PORT:-3001}:3000
    depends_on:
      - db
      - redis
  #    environment:
  #      - REDIS_URL_CACHING=redis://redis:6379/0

  adminer:
    image: adminer:4.8.1
    ports:
      - ${ADMINER_PORT:-8080}:8080

volumes:
  db: null
  redis: null